[package]
name = "good_morning"
version = "0.1.0"
license = "MIT"
authors = ["Jason Willems <jason@willems.ca>"]

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2.2"
image = "0.13"
imageproc = { git = "https://github.com/at1as/imageproc" }
rusttype = "0.2"
serde_json = "0.9"

